#!/bin/sh

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-/opt/glite/var}

[ -f /etc/glite.conf ] && . /etc/glite.conf
[ -f $GLITE_LOCATION/etc/glite-wms.conf ] && . $GLITE_LOCATION/etc/glite-wms.conf
[ -f $HOME/.glite.conf ] && . $HOME/.glite.conf

PROXY_REPOSITORY="$GLITE_LOCATION_VAR/spool/glite-renewd"

unset creds

start()
{
	if test -z "$GLITE_USER" ;then
		echo 'Error: GLITE_USER is not set'
		echo FAILED
		return 1
	fi

	[ -n "$GLITE_HOST_CERT" -a -n "$GLITE_HOST_KEY" ] &&
		creds="-t $GLITE_HOST_CERT -k $GLITE_HOST_KEY"

	if test -z "$creds"; then
		if su - $GLITE_USER -c "test -r /etc/grid-security/hostkey.pem -a -r /etc/grid-security/hostcert.pem"; then
			echo "$0: WARNING: /etc/grid-security/hostkey.pem readable by $GLITE_USER"
			creds="-t /etc/grid-security/hostcert.pem -k /etc/grid-security/hostkey.pem"
		fi
	fi

	[ -z "$creds" ] &&
		echo $0: WARNING: No credentials specified. Using default lookup which is dangerous. >&2

	# workaround for VOMS_FindByVO that seems to always require user's own VOMS config file (bug #7511)
	user_voms_config=$HOME/.glite/vomses
	if [ ! -f "$user_voms_config" ]; then
		rm -f /tmp/renewal_vomses
		su - $GLITE_USER -c "touch /tmp/renewal_vomses && chmod 644 /tmp/renewal_vomses"
		user_voms_config=/tmp/renewal_vomses
	fi

	echo -n Starting ProxyRenewal Daemon: glite-proxy-renewd ...

	if [ ! -d "$PROXY_REPOSITORY" ]; then
		mkdir -p $PROXY_REPOSITORY || exit 1
		chown $GLITE_USER $PROXY_REPOSITORY
		chmod 0700 $PROXY_REPOSITORY
	fi
	
	su - $GLITE_USER -c "VOMS_USERCONF=$user_voms_config \
		$GLITE_LOCATION/bin/glite-proxy-renewd \
		-r $PROXY_REPOSITORY $creds -A" && echo " done"
}

stop()
{
	echo -n "Stopping ProxyRenewal Daemon: glite-proxy-renewd ..."
	killall glite-proxy-renewd
	echo " done"
}

status()
{
	if netstat -an --unix | grep "^unix .* LISTEN.* /tmp/dgpr_renew_" >/dev/null 2>&1 ;then
		echo glite-proxy-renewd running
	else
		echo glite-proxy-renewd not running
		return 1
	fi
}

case x$1 in
	xstart) start;;
	xstop)  stop;;
	xrestart) stop; start;;
	xstatus) status;;
	x*)	echo usage: $0 start,stop,restart,status >&2
		exit 1;;
esac
