top_srcdir=..
stagedir=.
package=emi-px
version=0.0.0
PREFIX=/opt/glite
prefix=

-include Makefile.inc
-include ../project/version.properties

default all:

install:

stage:
	$(MAKE) install PREFIX=${stagedir}

check:

clean:

distclean:
	rm -rvf Makefile.inc *.spec debian/

.PHONY: default all check install stage clean distclean
